### ISSUE TITLE
Paper Discussion Group Page

### ISSUE THREAD

**Issue by MarvinTeichmann** [ML-KA/ML-KA.github.io#7]
The Page http://ml-ka.de/paper-discussion-group/ does not work. Commit  f10cc12939091d2fbdd2d2195e74c4b892f4dbc7 should include this page. See also 6c10e06c178549e6023433d733ae4365ae541e09.

Have I done somethink wrong?

**Comment by MartinThoma** [comment]
I guess you before it. The CNAME file has to be in the root in master. I'll
have a look at it tomorrow

**Comment by MartinThoma** [comment]
Fixed with https://github.com/ML-KA/ML-KA.github.io/commit/8bade85028bbea09437ba6a718d67050f611ab76
